import React, { useState } from "react";
import './App.css';
import ReactGlobe from "react-globe";

import "tippy.js/dist/tippy.css";
import "tippy.js/animations/scale.css";

import defaultMarkers from "./markers";

function markerTooltipRenderer(marker) {
    return `CITY: ${marker.city} (Value: ${marker.value})`;
}

const options = {
    markerTooltipRenderer
};

function App() {
    const [markers, setMarkers] = useState([
        defaultMarkers
    ]);
    const [event, setEvent] = useState(null);
    const [details, setDetails] = useState(null);
    function onClickMarker(marker, markerObject, event) {
        setEvent({
            type: "CLICK",
            marker,
            markerObjectID: markerObject.uuid,
            pointerEventPosition: { x: event.clientX, y: event.clientY }
        });
        setDetails(markerTooltipRenderer(marker));
    }
    function onDefocus(previousFocus) {
        setEvent({
            type: "DEFOCUS",
            previousFocus
        });
        setDetails(null);
    }

  return (
      <div className="container">
        <div>
          <title>No More Points on this map</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/325/globe-showing-europe-africa_1f30d.png"/>
        </div>

        <main className="main">
          <h1 className="title">
            No more points on this map
          </h1>

          <p className="description">
            The IPCC is clear, greehouse gas emissions intensifies specific weather and climate events such as extreme heat waves and heavy rainfall events. Please stop burning fossil fuels and save me from adding points on this chart.
          </p>
        </main>

          {details && (
              <div
                  style={{
                      background: "rgb(22, 27, 34)",
                      color: 'white',
                      position: "absolute",
                      bottom: 0,
                      right: '3rem',
                      padding: 20,
                      borderRadius: 6,
                      border: '1px solid #30363D'
                  }}
              >
                  <p style={{
                      margin: 0
                  }}>{details}</p>
                  <p style={{
                      margin: 0
                  }}>
                      EVENT: type={event.type}, position=
                      {JSON.stringify(event.pointerEventPosition)})
                  </p>
              </div>
          )}
          <ReactGlobe
              height="100vh"
              markers={defaultMarkers}
              options={options}
              width={'100%'}
              onClickMarker={onClickMarker}
              onDefocus={onDefocus}
          />

        <footer className="footer">
          <div>
            Made with love/passion by <a target="_blank" rel="noreferrer" href="https://github.com/alexandre-mace">@alexandre-mace</a>
          </div>
        </footer>
      </div>
  );
}

export default App;
